// Build step: src/dsh/Files.css is the source of truth for the client's
// styles. The dsh web shell's module loader has no asset pipeline, so the
// styles must ship inside the client bundle: this script embeds the CSS into
// src/dsh/files-css.generated.ts (a committed, deterministic module) that
// client.tsx imports. Runs first in `npm run build`; the output is only
// rewritten when the CSS changed.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const cssPath = join(root, "src", "dsh", "Files.css");
const outPath = join(root, "src", "dsh", "files-css.generated.ts");

const css = readFileSync(cssPath, "utf8").replace(/\r\n/g, "\n").replace(/\s+$/, "");
// Count braces in the rules, not the comments: a truncated CSS file would
// otherwise only fail at browser runtime.
const bare = css.replace(/\/\*[\s\S]*?\*\//g, "");
const open = (bare.match(/{/g) || []).length;
const close = (bare.match(/}/g) || []).length;
if (open !== close) {
  console.error(`inject-css: unbalanced braces in ${cssPath} (${open} { vs ${close} })`);
  process.exit(1);
}
const escaped = css.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
const out =
  "// GENERATED by scripts/inject-css.mjs — do not edit; edit src/dsh/Files.css\n" +
  "// and re-run `npm run build`.\n" +
  "export const css = `" + escaped + "`;\n";
const prev = existsSync(outPath) ? readFileSync(outPath, "utf8") : null;
if (prev !== out) {
  writeFileSync(outPath, out);
  console.log(`inject-css: wrote ${outPath} (${Buffer.byteLength(out)} bytes)`);
} else {
  console.log("inject-css: up to date");
}
